# Generated by Django 5.1.5 on 2026-01-25 14:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Original filename", max_length=255),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="CSV file containing equipment data",
                        upload_to="datasets/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["csv"]
                            )
                        ],
                    ),
                ),
                (
                    "row_count",
                    models.IntegerField(
                        default=0, help_text="Number of equipment records"
                    ),
                ),
                ("total_equipment", models.IntegerField(default=0)),
                ("avg_flowrate", models.FloatField(blank=True, null=True)),
                ("avg_pressure", models.FloatField(blank=True, null=True)),
                ("avg_temperature", models.FloatField(blank=True, null=True)),
                ("file_size", models.IntegerField(help_text="File size in bytes")),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="datasets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dataset",
                "verbose_name_plural": "Datasets",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="AnalyticsLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("action", models.CharField(db_index=True, max_length=50)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.dataset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Analytics Log",
                "verbose_name_plural": "Analytics Logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("equipment_name", models.CharField(db_index=True, max_length=255)),
                ("equipment_type", models.CharField(db_index=True, max_length=100)),
                ("flowrate", models.FloatField(help_text="Flow rate value")),
                ("pressure", models.FloatField(help_text="Pressure value")),
                ("temperature", models.FloatField(help_text="Temperature value")),
                (
                    "unit_flowrate",
                    models.CharField(blank=True, default="L/min", max_length=20),
                ),
                (
                    "unit_pressure",
                    models.CharField(blank=True, default="Bar", max_length=20),
                ),
                (
                    "unit_temperature",
                    models.CharField(blank=True, default="°C", max_length=20),
                ),
                (
                    "row_number",
                    models.IntegerField(help_text="Original row number in CSV"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment_records",
                        to="api.dataset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipment Record",
                "verbose_name_plural": "Equipment Records",
                "ordering": ["dataset", "row_number"],
            },
        ),
        migrations.CreateModel(
            name="EquipmentTypeDistribution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("equipment_type", models.CharField(max_length=100)),
                ("count", models.IntegerField()),
                ("percentage", models.FloatField()),
                ("avg_flowrate", models.FloatField(blank=True, null=True)),
                ("avg_pressure", models.FloatField(blank=True, null=True)),
                ("avg_temperature", models.FloatField(blank=True, null=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="type_distributions",
                        to="api.dataset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipment Type Distribution",
                "verbose_name_plural": "Equipment Type Distributions",
                "ordering": ["-count"],
            },
        ),
        migrations.AddIndex(
            model_name="dataset",
            index=models.Index(
                fields=["-uploaded_at"], name="api_dataset_uploade_babbef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dataset",
            index=models.Index(
                fields=["processing_status"], name="api_dataset_process_3c3a2a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="equipment",
            index=models.Index(
                fields=["dataset", "equipment_type"],
                name="api_equipme_dataset_5f63bb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="equipment",
            index=models.Index(
                fields=["equipment_name"], name="api_equipme_equipme_e29dda_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="equipmenttypedistribution",
            unique_together={("dataset", "equipment_type")},
        ),
    ]
